export const JIGSAW_CHANGE_FILE = 'JIGSAW_CHANGE_FILE';
export const JIGSAW_STATUS_CHANGE = 'JIGSAW_STATUS_CHANGE';
export const JIGSAW_SETTINGS_CHANGE = 'JIGSAW_SETTINGS_CHANGE';

export const NAVIGATION_MENU_TOGGLE = 'NAVIGATION_MENU_TOGGLE';
